apiVersion: v1
kind: Service
metadata:
  name: guestbook-frontend
  labels: 
    app: guestbook
    
    tier: frontend 

spec:
  selector:
    app: guestbook
    
    tier: frontend
  ports:
  - port: 80
    

    

