apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  labels: 
    app: redis
    role: head
    tier: backend 

spec:
  selector:
    app: redis
    role: head
    tier: backend
  ports:
  - port: 6379
    targetPort: 6379

    

